//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 02:08:47 PM WAT 
//


package all.webservice.isante.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the all.webservice.isante.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: all.webservice.isante.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateBankingInfoRequest }
     * 
     */
    public UpdateBankingInfoRequest createUpdateBankingInfoRequest() {
        return new UpdateBankingInfoRequest();
    }

    /**
     * Create an instance of {@link AddBankingInfoRequest }
     * 
     */
    public AddBankingInfoRequest createAddBankingInfoRequest() {
        return new AddBankingInfoRequest();
    }

    /**
     * Create an instance of {@link AddBankingInfoResponse }
     * 
     */
    public AddBankingInfoResponse createAddBankingInfoResponse() {
        return new AddBankingInfoResponse();
    }

    /**
     * Create an instance of {@link GetBankingInfoByMemberId }
     * 
     */
    public GetBankingInfoByMemberId createGetBankingInfoByMemberId() {
        return new GetBankingInfoByMemberId();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link BankingInfo }
     * 
     */
    public BankingInfo createBankingInfo() {
        return new BankingInfo();
    }

    /**
     * Create an instance of {@link GetBankingInfoResponse }
     * 
     */
    public GetBankingInfoResponse createGetBankingInfoResponse() {
        return new GetBankingInfoResponse();
    }

    /**
     * Create an instance of {@link UpdateBankingInfoResponse }
     * 
     */
    public UpdateBankingInfoResponse createUpdateBankingInfoResponse() {
        return new UpdateBankingInfoResponse();
    }

}
