//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 02:08:47 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.isante.webservice.all", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package all.webservice.isante.com;
